# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/posts", type: :request do
  let!(:user) { create :user }

  # This should return the minimal set of attributes required to create a valid
  # Post. As you add validations to Post, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { user_id: user.id, title: "MyPostTitle", content: "MyPostBody", status: :public } }

  let(:invalid_attributes) { { title: "<MyPostTitle>", content: "MyPostBody" } }

  before { sign_in(user) }

  describe "GET /index" do
    before do
      build_stubbed_list(:post, 2, user:)
      get posts_url
    end

    it "renders a successful response" do
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    let!(:post) { create :post, user: }

    before { get post_url(post) }

    it "renders a successful response" do
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_post_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    let!(:post) { create :post, user: }

    before { get edit_post_url(post) }

    it "renders a successful response" do
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Post" do
        expect { post posts_url, params: { post: valid_attributes } }.to change(Post, :count).by(1)
      end

      it "redirects to the created post" do
        post posts_url, params: { post: valid_attributes }
        expect(response).to redirect_to(post_url(Post.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Post" do
        expect do post posts_url, params: { post: invalid_attributes } end.not_to change(Post, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post posts_url, params: { post: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    let!(:post) { create :post, user: }
    let(:new_attributes) { { title: "MyPostTitle2" } }

    context "with valid parameters" do
      let(:new_attributes) { { title: "MyPostTitle2", content: "MyPostBody2" } }

      it "updates the requested post" do
        expect { patch post_url(post), params: { post: new_attributes } }.to(
          change { post.reload.title }.to("MyPostTitle2")
        )
      end

      it "redirects to the post" do
        patch post_url(post), params: { post: new_attributes }
        post.reload
        expect(response).to redirect_to(post_url(post))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        patch post_url(post), params: { post: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    let!(:post) { create :post, user: }

    it "destroys the requested post" do
      expect { delete post_url(post) }.to change(Post, :count).by(-1)
    end

    it "redirects to the posts list" do
      delete post_url(post)
      expect(response).to redirect_to(posts_url)
    end
  end
end
