default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 5
      processes: 1
      polling_interval: 0.1
    - queues: [turbo_streams_*, real_time, background]
      threads: 5
      polling_interval: 0.1
      processes: 3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
